### PR TITLE
Fix OCR-D

### PR DESCRIPTION
**Pull request by bertsky**
This addresses two issues:

1. The `@imageFilename` references cannot be handled by OCR-D (core, browser, processors), because they are neither available in the filesystem nor (as URLs) in the METS. They have obviously been "inspired" by the `@CONTENTIDS` in the METS, but are not string-identical (and we have no tool support for that kind of correspondence anyway).
   - The fix is to write the corresponding URL ref from OCR-D-IMG into the PAGE file.
2. A few coordinate invalidities and inconsistencies remain, which may cause problems – depending on the use-case.
   - The fix uses ocrd-segment-repair to run the PageValidator and attempt direct repairs whereever possible.

My PR tries to minimise the changeset (by reproducing the same NS prefixes and indentations), but due to the nature of schema-generated serialised XML, some cosmetic differences remain.

If you wish, I can do the same with the other repos.

### CODE REVIEW

**Comment by bertsky** [comment]
Here is the [report.zip](https://github.com/ulb-sachsen-anhalt/ulb-groundtruth-eval-odem-ger/files/15501737/report.zip) of the PageValidator (`ocrd workspace -d data/ger validate -s imagefilename -s pixel_density -s mets_fileid_page_pcgtsid --page-textequiv-consistency strict --page-strictness strict --page-coordinate-consistency both > report.xml`).

**Comment by M3ssman** [comment]
Thanks you for contributing!
Before applying I will take a closer look at the report data and so some comparisons with recent [digital-eval](https://github.com/ulb-sachsen-anhalt/digital-eval) to see if it has measurable effects, since consistent QA is my main concern. 

On first sight I noticed several ID-errors which *usually* indicate duplicates within the METS-file, which shouldn't happen of course. Maybe there's a even severe problem in the way the METS got assembled. 
For the inconsistencies concerning image heights, it's like @stweil noted: it's from the image's footer, which gets ignored during OCRing. I'm not sure whether this is a real problem.

**Comment by bertsky** [comment]
> On first sight I noticed several ID-errors which _usually_ indicate duplicates within the METS-file, which shouldn't happen of course. Maybe there's a even severe problem in the way the METS got assembled.

It's only affecting the logical divs, but yes, these do clash (same logical div used for successive physical pages).

The other errors (see report here or repair log in the other repo) mostly concern coordinate consistency (words not properly contained in the line or lines not contained in the region), invalid polygon paths, and textual consistency (region level does not seem to have been projected from line level after last changes).

> For the inconsistencies concerning image heights, it's like @stweil noted: it's from the image's footer, which gets ignored during OCRing. I'm not sure whether this is a real problem.

It's not, fortunately. Earlier we decided not to "look" at these attributes in core's image/coordinate functions, but always determine the actual image's size. So these only worry the validator.

**Comment by M3ssman** [comment]
There are minimal differences for arithmetical mean and std since the numbers of characters differ slightly
```
digital-eval /data/ocr/media/jpg/odem/ger -ref ../ulb-groundtruth-eval-odem-ger/data/ger
[INFO ] Evaluation Summary (candidates: "/data/ocr/media/jpg/odem/ger" vs. reference: "../ulb-groundtruth-eval-odem-ger/data/ger" (2024-10-23)
[INFO ] Cs@ger	 1026 items 1_667_674 refs	∅:94.18 M:97.51 σ:11.43
[INFO ] Cs@ger(-119)	 907 items 1_457_326 refs	∅:97.18 M:97.89 σ: 2.14
[INFO ] Ls@ger	 1026 items 1_316_713 refs	∅:95.11 M:98.35 σ:11.09
[INFO ] Ls@ger(-119)	 907 items 1_154_126 refs	∅:97.92 M:98.55 σ: 1.91

digital-eval /data/ocr/media/jpg/odem/ger -ref ../bertsky-ulb-groundtruth-eval-odem-ger/data/ger
[INFO ] Evaluation Summary (candidates: "/data/ocr/media/jpg/odem/ger" vs. reference: "../bertsky-ulb-groundtruth-eval-odem-ger/data/ger" (2024-10-23)
[INFO ] Cs@ger	 1026 items 1_666_297 refs	∅:94.26 M:97.53 σ:11.38
[INFO ] Cs@ger(-119)	 907 items 1_458_513 refs	∅:97.21 M:97.89 σ: 2.09
[INFO ] Ls@ger	 1026 items 1_315_736 refs	∅:95.16 M:98.35 σ:11.06
[INFO ] Ls@ger(-117)	 909 items 1_158_420 refs	∅:97.93 M:98.55 σ: 1.89
```

**Pull request merged**
